### ISSUE TITLE
None.get(): undefined is incompatible with never

### ISSUE THREAD

**Issue by ghlin** [AlexGalays/spacelift#1]
doesn't compile:
```
error TS2430: Interface 'None' incorrectly extends interface 'Option<never>'.
  Types of property 'get' are incompatible.
    Type '() => undefined' is not assignable to type '() => never'.
      Type 'undefined' is not assignable to type 'never'.
```

**Comment by AlexGalays** [comment]
Weird I didn't see this. Which tsc version do you use?

**Comment by ghlin** [comment]
tsc Version 2.3.2

**Comment by AlexGalays** [comment]
Same version `space-lift` uses to compile its src and tests. The `npm run build` command sets 3 tsc flags: 

```
--noImplicitAny
--strictNullChecks
--suppressImplicitAnyIndexErrors
```

With these flags, the compilation succeeds.

If we remove --strictNullChecks, then I get your error.

**Comment by ghlin** [comment]
It works. Thank you! :smile:

**Comment by zsoltm** [comment]
I have the same issue, problem is I couldn't just turn on `--strictNullChecks` as we have a relatively big code base. Would be nice if the lib would be less restrictive on compiler options, how about:

```
export interface None extends Option<never> {
    type: 'none';
    get(): never;
}
```
?

**Comment by AlexGalays** [comment]
Hummm, but None really does return undefined :(
