### ISSUE TITLE
Option.toResult and Result.toMaybe

### ISSUE THREAD

**Issue by sporto** [AlexGalays/spacelift#10]
Nice lib!

When working with function than return Option or Result it is very useful to convert one to the other. In that way is possible to chain these e.g.

```
Some(34)
    .toResult("No number")
    .flatMap(n => Ok(x * 2))
```

See
http://package.elm-lang.org/packages/elm-lang/core/latest/Result#fromMaybe
https://doc.rust-lang.org/core/option/enum.Option.html#method.ok_or

`Result.toMaybe` would also be great.
https://doc.rust-lang.org/core/result/enum.Result.html#method.ok

Please consider adding these.

**Comment by AlexGalays** [comment]
Thanks :)

I refrained from adding those till I felt it was really necessary. The reasoning was that with an OO style, importing Option would always mean also importing Result with it, increasing your bundle size if you only wanted to use one of the two.

However, thinking about it some more... the two implementations are so tiny that I think the interop has more pros than cons.

**Comment by sporto** [comment]
Thanks. I use these all the time in Elm and Rust. For me they feel necessary when you start returning Option or Result from most of your functions.

**Comment by AlexGalays** [comment]
Added in version 0.8.0!

**Comment by sporto** [comment]
Great thanks. Seems to be missing from the docs.
