### ISSUE TITLE
Option (and whatever else) missing

### ISSUE THREAD

**Issue by otto-dev** [AlexGalays/spacelift#18]
Posting this here mainly for others. I spent considerable time trying to make my `import` statement work without success.

Turns out that the `latest` tag on `npm` is pointing to `1.0.0-beta.3`. This version does not contain [all] the classes of the `0.8.x` version listed in the README. So if something is missing, downgrade to `0.8.7` and you'll be fine.

Would be good to fix the `latest` tag on npm until the 1.x series actually has a release.

**Comment by saemie** [comment]
I had this same issue.

**Comment by AlexGalays** [comment]
Cheers,

To be honest I didn't even know about that dynamic `latest` tag. I put it back on the `0.8.7` version and will explicitely tag the  new 1.x.x branch releases with `beta` and will only resume tagging that as the `latest` once the README is updated.

Full disclosure though: version 1.x.x indeed won't have `Option` (nor `Result`) as after quite a few projects' worth of feedback plus the addition of `?.` in the language, I feel like it's no longer offsetting the choice burden it adds on top of `T | undefined` or `?: T`. But of course you can still use version `0.8.7`.

**Comment by otto-dev** [comment]
> Do you think it's a mistake to remove `Option`?

Of course it is!

`Option` is both more explicit and more expressive than the `null` syntax.

Compare 
```ts
const a = mayFailA('x');
if (a !== undefined) {
  const b = mayFailB(a);
  if (b !== undefined) {
    const c = mayFailC(b);
    if (c !== undefined) console.log(c);
  }
}
```

With 

```ts
mayFailA('x')
  .flatMap(mayFailB)
  .flatMap(mayFailC)
  .forEach(console.log);
```

**Comment by otto-dev** [comment]
`orElse` example:

```ts
function go(x: string) {
  const a = mayFailA(x);
  if (a !== undefined) {
    const b = mayFailB(a);
    if (b !== undefined) {
      const c = mayFailC(b);
      if (c !== undefined) return c;
    }
  }
  return attemptTwo(x);
}
console.log(go('x'));
```
vs
```ts
mayFailA('x')
  .flatMap(mayFailB)
  .flatMap(mayFailC)
  .orElse(() => attemptTwo('x'))
  .forEach(console.log);
```
