### ISSUE TITLE
Depend on @types/mocha via package.json?

### ISSUE THREAD

**Issue by chriskrycho** [AlexGalays/spacelift#2]
Instead of vendoring Mocha's types, would you be up for a PR that pulled them in using `@types/mocha` in the package.json? Happy to do that legwork myself, probably mid-to-late next week.

**Comment by AlexGalays** [comment]
Sorry for the late reply!

I've lost the habit of depending on @types externally as historically, I often had to fiddle with global type definitions anyway (poorly written or completely missing types, or typing custom things injected by the webpack build process, etc)

For a lib, it should be just fine though!

**Comment by chriskrycho** [comment]
Heh, no worries. As a maintainer of typings myself, that’s super true.

In this case, after lots of poking and experimenting, I did what all good nerds do and [built my own library](https://github.com/chriskrycho/true-myth), so it’s no longer something I’m feeling as a pain point personally! :laughing:

**Comment by AlexGalays** [comment]
Wow nice !

Closing for now then.
