### ISSUE TITLE
Please do not remove Option and Result from this library

### ISSUE THREAD

**Issue by otto-dev** [AlexGalays/spacelift#21]
Follow up issue on #18 

> Version 1.x.x won't have `Option` (nor `Result`) as [...]  the addition of `?.` in the language, I feel like it's no longer offsetting the choice burden it adds on top of `T | undefined` or `?: T`.

I disagree with this conclusion. `Option` is both more explicit and more expressive than the `undefined` syntax. `Option` allows you to compose functions in ways that `undefined` just does not have a comparable API for.

Compare (`undefined` version)
```ts
function go(x: string) {
  const a = mayFailA(x);
  if (a !== undefined) {
    const b = mayFailB(a);
    if (b !== undefined) {
      const c = mayFailC(b);
      if (c !== undefined) return c;
    }
  }
  return attemptTwo(x);
}
const result = go('x')
if(result !== undefined) console.log(result);
```
with (`Option` version), same logic

```ts
mayFailA('x')
  .flatMap(mayFailB)
  .flatMap(mayFailC)
  .orElse(() => attemptTwo('x'))
  .forEach(console.log);
```

This is currently my go-to lightweight library for `Option` and `Result`. I argue if those fundamental monads should be removed, it should be published under a new name, rather than as an "upgrade".

**Comment by AlexGalays** [comment]
I see where you're coming from.

However,

- There is no denying that your chosen example plays to the strengths of having Options returned everywhere in one's app and that _once_ you're very familiar with it, it has mostly pros and little cons. Many people are not familiar with it though and it's easy to make a case for our app's abstraction levels to remain as low as possible.

If I rewrite your exemple using an early return style, rather common with JS devs, it would look like something like this:

```ts
function go(x: string) {
  const a = mayFailA(x);
  if (a === undefined) return;

  const b = mayFailB(a);
  if (b === undefined) return;

  const c = mayFailC(b);
  if (c !== undefined) return c;
}

const maybeResult = go('x')
const result = maybeResult !== undefined
  ? maybeResult
  : `attemptTwo('x')`
if (result !== undefined)  console.log(result)
```

More lines but pretty readable, right? It could be further shortened if the mayFail functions returned something compatible with truthy/falsy checks (so not strings or numbers)

- JS/TS doesn't have first-class support for monad chaining so your neat example becomes much harder to read if earlier results/dependencies must also be passed to later steps (e.g, if `mayFailC` requires both an `a` and `b`)
Some people have tried to code for-comprehensions in user-land, but let's be honest, it's [atrocious](https://gcanti.github.io/fp-ts-contrib/modules/Do.ts.html)

- `Option<T>` is an alternative to modelling as `T | undefined` which has good support in `TS` and everyone understand. For `Option`  to be really successful and at its most useful on a project, everyone has to agree and constantly pick it over `T | undefined`, everytime. In my experience, this doesn't happen with most people writing JavaScript. This also adds to the burden of choice. 

- I like neat libs and I'm always trying to remove what doesn't fully carry its weight. 

I realise it's a compromise and that for someone already familiar with monads working alone or with like-minded people, this must look like a weird decision. Likewise if you _only_ used space-lift for that.

As for the name, I quite like it so I would like to keep using it for what I think will be the first stable version. Plus, everything else remains (methods à la lodash, immutable updates, etc)
Perhaps you can fork version `0.8.7` and publish it under another name?

**Comment by otto-dev** [comment]
Both imperative and functional styles of programming have pros and cons and you can achieve the same with either. You personally don't like using monads anymore in your code for practical and philosophical reasons - no issues with that.

The problem is that this little library is currently downloaded close to 1000 times per week on npm by many people like me who want to use monads. You do have the right to remove these (to them) central features, but it's not what should happen from an open-source perspective. There is an implicit trust-contract that is being broken, and it's frankly a choice that you shouldn't make for them because of a shift in personal preference.

I can hear you say "people can still use `0.8.7`", but in reality nobody wants to use a library version that is no longer maintained and supported.

> Perhaps you can fork version 0.8.7 and publish it under another name?

I'd be more than happy to take over the maintenance of the 0.x series if it's done properly. That is, people who are currently using this library, whose code will stop compiling once you push your update, have to be able to find it easily. Ideally the current `space-lift` npm module should continue to point to the 0.x series which I'm happy to maintain in this or another repository. If this is not possible then there should be at least a bold note on the beginning of the `README` that the old version of this library has moved.
