### ISSUE TITLE
Cannot use library

### ISSUE THREAD

**Issue by chodorowicz** [AlexGalays/spacelift#5]
Hey!
Thanks for your work! 

I came back to `space-lift` after some time and I cannot really run it. I immediately get errors when trying to run examples.

> index.ts(10,4): error TS2339: Property 'findIndex' does not exist on type 'ArrayOps<{ id: number; name: string; }>'.
> index.ts(11,30): error TS2339: Property 'updateAt' does not exist on type 'ArrayOps<{ id: number; name: string; }>'.

You can also see it some online coding environments.  https://codesandbox.io/s/4xn0zj3o40

> space_lift_1.default(...).findIndex is not a function

```ts
import lift, { update } from 'space-lift'

const people = [
  { id: 1, name: 'jon' },
  { id: 2, name: 'sarah' },
  { id: 3, name: 'nina' }
]

const updatedPeople = lift(people)
  .findIndex(p => p.id === 2)
  .map(index => lift(people).updateAt(index, person => update(person, { name: 'Nick' })))
  .getOrElse(people)
```

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "tsc": "tsc" 
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "space-lift": "^0.6.5",
    "typescript": "^2.7.2"
  }
}
```

**Comment by AlexGalays** [comment]
You're missing a step documented in : https://github.com/AlexGalays/spacelift#how-to-use

Apparently, codesandbox doesn't know how to deal with ES modules so you can use

import "space-lift/commonjs/all";

**Comment by chodorowicz** [comment]
Of course! Thanks and sorry for an unnecessary issue! Greetings!

**Comment by AlexGalays** [comment]
No problem, cheers :)
